#!/usr/bin/env node
/** Portable systemd deployment; private host policy belongs to the caller. */
import { execFileSync } from "node:child_process";
import { chmodSync, chownSync, lstatSync, mkdirSync, readFileSync, realpathSync, renameSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const packageDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repoDir = resolve(packageDir, "../..");

function statOrNull(path) {
  try { return lstatSync(path); } catch (error) {
    if (error.code === "ENOENT") return null;
    throw error;
  }
}

function absolutePath(value, label) {
  if (!/^\/[A-Za-z0-9_./-]+$/.test(value) || value.split("/").includes("..") || value.includes("//")) {
    throw new Error(`${label} must be an absolute literal path without whitespace, specifiers or traversal.`);
  }
  return resolve(value);
}

export function deploymentPlan(options) {
  const uid = Number(options.uid), gid = Number(options.gid);
  if (!/^[0-9]+$/.test(String(options.uid)) || !/^[0-9]+$/.test(String(options.gid)) ||
      !Number.isSafeInteger(uid) || !Number.isSafeInteger(gid) || uid < 1 || gid < 1 || uid > 4294967294 || gid > 4294967294) {
    throw new Error("Explicit non-root --uid and --gid are required.");
  }
  const bridgeDir = absolutePath(options.bridgeDir ?? `/tmp/agent-mesh-${uid}`, "bridge directory");
  const tmuxDir = absolutePath(options.tmuxDir ?? `/tmp/tmux-${uid}`, "tmux directory");
  for (const path of [bridgeDir, tmuxDir]) {
    if (!/^\/tmp\/[A-Za-z0-9_-]+$/.test(path)) throw new Error("Runtime directories must be distinct direct children of /tmp.");
  }
  if (bridgeDir === tmuxDir) throw new Error("Bridge and tmux directories must differ.");
  const rulePath = `/etc/tmpfiles.d/agent-mesh-${uid}.conf`;
  const files = [{ path: rulePath, content:
    `# Generated by Agent Mesh. Recreate runtime directories before services start.\n` +
    `d ${bridgeDir} 0700 ${uid} ${gid} -\nd ${tmuxDir} 0700 ${uid} ${gid} -\n` }];
  const plan = { uid, gid, bridgeDir, tmuxDir, rulePath, files };
  if (options.directoriesOnly) return plan;

  const releaseDir = absolutePath(options.releaseDir ?? repoDir, "release directory");
  const stateDir = absolutePath(options.stateDir ?? "/var/lib/agent-mesh-mcp", "state directory");
  const values = {
    UID: uid, GID: gid, RELEASE_DIR: releaseDir, STATE_DIR: stateDir,
    CONFIG: absolutePath(options.config ?? "/etc/agent-mesh-mcp/runtime.json", "config"),
    ENVIRONMENT_FILE: absolutePath(options.environmentFile ?? "/etc/agent-mesh-mcp/environment", "environment file"),
    NODE: absolutePath(options.node ?? process.execPath, "Node executable"),
    BRIDGE_DIR: bridgeDir, TMUX_PARENT: dirname(tmuxDir),
    WRITE_PATHS: [...new Set([stateDir, bridgeDir, tmuxDir, ...(options.writePaths ?? []).map(p => absolutePath(p, "write path"))])].join(" ")
  };
  // tmux itself appends tmux-<uid> to TMUX_TMPDIR; it needs this exact path.
  if (tmuxDir !== `/tmp/tmux-${uid}`) throw new Error("The standalone unit requires the standard tmux-<uid> directory.");
  const template = readFileSync(join(packageDir, "deploy/agent-mesh-mcp.service.in"), "utf8");
  files.push({ path: "/etc/systemd/system/agent-mesh-mcp.service", content:
    template.replace(/@([A-Z_]+)@/g, (_, key) => {
      if (!(key in values)) throw new Error(`Unknown template value: ${key}`);
      return String(values[key]);
    }) });
  return { ...plan, stateDir };
}

export function installDeployment(plan, root = "/") {
  root = absolutePath(root === "/" ? "/." : root, "root");
  if (root === "/" && process.getuid() !== 0) throw new Error("Live --apply requires root; review the plan before using sudo.");
  const target = path => join(root, path);
  // Validate all destinations before writing. Never follow a runtime-directory symlink.
  for (const path of [plan.bridgeDir, plan.tmuxDir, ...(plan.stateDir ? [plan.stateDir] : [])]) {
    const stat = statOrNull(target(path));
    if (stat !== null) {
      if (!stat.isDirectory() || stat.isSymbolicLink() || stat.uid !== plan.uid) {
        throw new Error(`Refusing unsafe or differently owned runtime directory: ${path}`);
      }
    }
  }
  for (const file of plan.files) {
    const stat = statOrNull(target(file.path));
    if (stat !== null && !stat.isFile()) throw new Error(`Refusing non-regular destination: ${file.path}`);
  }
  for (const file of plan.files) {
    const destination = target(file.path);
    mkdirSync(dirname(destination), { recursive: true });
    const temporary = `${destination}.new-${process.pid}`;
    writeFileSync(temporary, file.content, { mode: 0o644, flag: "wx" });
    chmodSync(temporary, 0o644);
    renameSync(temporary, destination);
  }
  if (plan.stateDir) {
    mkdirSync(target(plan.stateDir), { recursive: true, mode: 0o750 });
    chownSync(target(plan.stateDir), plan.uid, plan.gid);
  }
  execFileSync("systemd-tmpfiles", ["--create", ...(root === "/" ? [] : ["--root", root]), target(plan.rulePath)], { stdio: "pipe" });
  for (const path of [plan.bridgeDir, plan.tmuxDir]) {
    const stat = lstatSync(target(path));
    if (!stat.isDirectory() || stat.uid !== plan.uid || stat.gid !== plan.gid || (stat.mode & 0o777) !== 0o700) {
      throw new Error(`Runtime-directory postcondition failed: ${path}`);
    }
  }
}

function main(args) {
  const options = { writePaths: [] };
  let apply = false, check = false, root = "/";
  const names = { "--uid": "uid", "--gid": "gid", "--bridge-dir": "bridgeDir", "--tmux-dir": "tmuxDir", "--release-dir": "releaseDir", "--state-dir": "stateDir", "--config": "config", "--environment-file": "environmentFile", "--node": "node" };
  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg === "--apply") apply = true;
    else if (arg === "--check") check = true;
    else if (arg === "--directories-only") options.directoriesOnly = true;
    else if (arg === "--help") {
      console.log("Usage: node install-systemd.mjs --uid UID --gid GID [--directories-only] [--release-dir DIR] [--state-dir DIR] [--config FILE] [--environment-file FILE] [--node FILE] [--write-path DIR] [--bridge-dir DIR] [--tmux-dir DIR] [--apply | --check] [--root TEST_ROOT]\nDefault: print an inert plan. Apply creates files/directories only; it does not start, enable or restart services.");
      return;
    } else if (arg in names || ["--root", "--write-path"].includes(arg)) {
      const value = args[++i];
      if (!value || value.startsWith("--")) throw new Error(`Missing value for ${arg}`);
      if (arg === "--root") root = value;
      else if (arg === "--write-path") options.writePaths.push(value);
      else options[names[arg]] = value;
    } else throw new Error(`Unknown option: ${arg}`);
  }
  if (apply && check) throw new Error("Choose --apply or --check.");
  const plan = deploymentPlan(options);
  root = absolutePath(root === "/" ? "/." : root, "root");
  if (check) {
    for (const file of plan.files) {
      if (readFileSync(join(root, file.path), "utf8") !== file.content) throw new Error(`Deployment differs: ${file.path}`);
    }
    for (const path of [plan.bridgeDir, plan.tmuxDir]) {
      const stat = lstatSync(join(root, path));
      if (!stat.isDirectory() || stat.uid !== plan.uid || stat.gid !== plan.gid || (stat.mode & 0o777) !== 0o700) throw new Error(`Runtime directory differs: ${path}`);
    }
    console.log("Agent Mesh systemd deployment matches.");
  } else if (apply) {
    installDeployment(plan, root);
    console.log(`Installed ${plan.files.map(file => file.path).join(", ")}; runtime directories ready.`);
  } else console.log(JSON.stringify(plan, null, 2));
}

if (process.argv[1] && import.meta.url === pathToFileURL(realpathSync(process.argv[1])).href) {
  try { main(process.argv.slice(2)); } catch (error) { console.error(error.message); process.exitCode = 1; }
}
